export const sliderItems = [
  {
    id: 1,
    img: 'https://i.ibb.co/GHGpPVn/Karim-Benzema-New-Real-Madrid-Shirt-2022-23.jpg',
    title: 'NEW SEASON SALE',
    description: 'Both player and fan version available with 30% discount.',
    bg: 'FDFDFD',
  },
  {
    id: 2,
    img: 'https://i.ibb.co/rtmJ1nN/FXJXnwu-WAAATWo-O-format-jpg-name-medium.jpg',
    title: 'BOTH COUNTRY AND CLUB JERSEY AVAILABLE',
    description: 'club and country jersey available with 30% discount.',
    bg: 'f3f9fc',
  },
  {
    id: 3,
    img: 'https://i.ibb.co/S3VZk8n/Manchester-City-Training-Men-s-Jersey.jpg',
    title: 'PRACTICE JERSEY ALSO AVAILABLE',
    description: 'All club practice jersey available.',
    bg: 'FAFAFA',
  },
];

export const categories = [
  {
    id: 1,
    img: 'https://i.ibb.co/KKrGVkL/01g363yr0cgkvy54nhxa.jpg',
    title: 'Laliga Jersey',
    category: 'Laliga',
  },
  {
    id: 2,
    img: 'https://i.ibb.co/KKrGVkL/01g363yr0cgkvy54nhxa.jpg',
    title: 'Premier League Jersey',
    category: 'Premier-League',
  },
  {
    id: 3,
    img: 'https://i.ibb.co/KKrGVkL/01g363yr0cgkvy54nhxa.jpg',
    title: 'SeriaA jersey',
    category: 'SeriaA',
  },
];

export const popularProducts = [
  {
    _id: '62d3930628bf5d100755b965',
    title: 'Liverpool',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/x5wrVvn/liverpool-22-23-home-kit-1.jpg',
    categories: ['Premier-League', 'England'],
    club: 'Liverpool',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away', 'Third'],
    price: 200,
    inStock: true,
    createdAt: '2022-07-17T04:41:42.419Z',
    updatedAt: '2022-07-17T04:41:42.419Z',
    __v: 0,
  },
  {
    _id: '62d3946d28bf5d100755b969',
    title: 'Manchester City',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/PWmCrwz/Manchester-City-presents-its-2022-2023-home-kit.jpg',
    categories: ['Premier-League', 'England'],
    club: 'Manchester-City',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away', 'Third'],
    price: 150,
    inStock: true,
    createdAt: '2022-07-17T04:47:41.309Z',
    updatedAt: '2022-07-17T04:47:41.309Z',
    __v: 0,
  },
  {
    _id: '62d3951528bf5d100755b96b',
    title: 'Chelsea',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/KzKxsCx/Whalefin-Chelsea-Sleeve-Sponsor-2022-23-624x443.jpg',
    categories: ['Premier-League', 'England'],
    club: 'Chelsea',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away'],
    price: 160,
    inStock: true,
    createdAt: '2022-07-17T04:50:29.854Z',
    updatedAt: '2022-07-17T04:50:29.854Z',
    __v: 0,
  },
  {
    _id: '62d395c528bf5d100755b96d',
    title: 'Arsenal',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/tq4FSn6/0-Introducing-the-new-Arsenal-2223-home-kit.jpg',
    categories: ['Premier-League', 'England'],
    club: 'Arsenal',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home'],
    price: 140,
    inStock: true,
    createdAt: '2022-07-17T04:53:25.952Z',
    updatedAt: '2022-07-17T04:53:25.952Z',
    __v: 0,
  },
  {
    _id: '62d3965a28bf5d100755b96f',
    title: 'Manchester United',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/jhv04jx/H23544-MUFC-FW22-HOME-KIT-ALEX-TELLES-093-s-RGB1657202650557-medium.jpg',
    categories: ['Premier-League', 'England'],
    club: 'Manchester United',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away', 'Third', ''],
    price: 140,
    inStock: true,
    createdAt: '2022-07-17T04:55:54.479Z',
    updatedAt: '2022-07-17T04:55:54.479Z',
    __v: 0,
  },
  {
    _id: '62d3977828bf5d100755b971',
    title: 'Real Madrid',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/n69WJkn/HA2664-42-detail.jpg',
    categories: ['Laliga', 'Spain'],
    club: 'Real Madrid',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away', 'Third'],
    price: 300,
    inStock: true,
    createdAt: '2022-07-17T05:00:40.585Z',
    updatedAt: '2022-07-17T05:00:40.585Z',
    __v: 0,
  },
  {
    _id: '62d3982328bf5d100755b973',
    title: 'Barcelona',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/x6QMBBh/2-FUUDC1s-WQAA3-SF2.jpg',
    categories: ['Laliga', 'Spain'],
    club: 'Barcelona',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away', 'Third'],
    price: 250,
    inStock: true,
    createdAt: '2022-07-17T05:03:31.210Z',
    updatedAt: '2022-07-17T05:03:31.210Z',
    __v: 0,
  },
  {
    _id: '62d398aa28bf5d100755b975',
    title: 'Atlatico Madrid',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://icdn.football-espana.net/wp-content/uploads/2022/06/FVJolDBWUAYQCbS.jpg',
    categories: ['Laliga', 'Spain'],
    club: 'Atlatico Madrid',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away'],
    price: 200,
    inStock: true,
    createdAt: '2022-07-17T05:05:46.777Z',
    updatedAt: '2022-07-17T05:05:46.777Z',
    __v: 0,
  },
  {
    _id: '62d39a7928bf5d100755b977',
    title: 'Juventus',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/CsrWk9z/juventus-22-23-kit-3.jpg',
    categories: ['SeriaA', 'Italy'],
    club: 'Juventus',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away'],
    price: 200,
    inStock: true,
    createdAt: '2022-07-17T05:13:29.513Z',
    updatedAt: '2022-07-17T05:13:29.513Z',
    __v: 0,
  },
  {
    _id: '62d39afb28bf5d100755b979',
    title: 'Ac Milan',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem tempora molestias pariatur corrupti dolor doloremque quibusdam eveniet autem eius modi.',
    img: 'https://i.ibb.co/pKWHKHC/1500x1000-Immagine-Orizzontale-2-f2f0211b-59ad-4009-8685-6ef2ea622caa.jpg',
    categories: ['SeriaA', 'Italy'],
    club: 'Ac Milan',
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    jerseyType: ['Home', 'Away'],
    price: 250,
    inStock: true,
    createdAt: '2022-07-17T05:15:39.365Z',
    updatedAt: '2022-07-17T05:15:39.365Z',
    __v: 0,
  },
];
